/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "cocktaildb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cocktaildb_ProductCode, cocktaildb_ProductCode, AUTO)


PB_BIND(cocktaildb_Ingredient, cocktaildb_Ingredient, AUTO)


PB_BIND(cocktaildb_Recipe, cocktaildb_Recipe, 2)


PB_BIND(cocktaildb_Qty, cocktaildb_Qty, AUTO)


PB_BIND(cocktaildb_RecipeStep, cocktaildb_RecipeStep, AUTO)


PB_BIND(cocktaildb_IngredientFile, cocktaildb_IngredientFile, 4)


PB_BIND(cocktaildb_RecipeFile, cocktaildb_RecipeFile, 4)


PB_BIND(cocktaildb_Equivalence, cocktaildb_Equivalence, AUTO)


PB_BIND(cocktaildb_MetaDataFile, cocktaildb_MetaDataFile, 4)




