#include "Settings.h"
#include <string.h>

static bool ValidateWifiPassword(const NVSJSON_SSettingEntry* pSettingEntry, const char* szValue);

NVSJSON_SHandle g_sSettingHandle;

static const NVSJSON_SSettingEntry g_sConfigEntries[SETTINGS_EENTRY_Count] =
{
    // WiFi Station related   
    [SETTINGS_EENTRY_WAPPass]      = NVSJSON_INITSTRING_VAL("WAP.Pass", "WiFi password [empty, or > 8 characters]", "!homer2008!", ValidateWifiPassword, NVSJSON_EFLAGS_Secret | NVSJSON_EFLAGS_NeedsReboot),

    // WiFi Station related
    [SETTINGS_EENTRY_WSTAIsActive] = NVSJSON_INITINT32_RNG( "WSTA.IsActive", "Wifi is active", 0, 0, 1, NVSJSON_EFLAGS_NeedsReboot),
    [SETTINGS_EENTRY_WSTASSID]     = NVSJSON_INITSTRING_RNG("WSTA.SSID",    "WiFi (SSID)", "", NVSJSON_EFLAGS_NeedsReboot),
    [SETTINGS_EENTRY_WSTAPass]     = NVSJSON_INITSTRING_VAL("WSTA.Pass", "WiFi password [empty, or > 8 characters]", "", ValidateWifiPassword, NVSJSON_EFLAGS_Secret | NVSJSON_EFLAGS_NeedsReboot),
    
    [SETTINGS_EENTRY_SLOT1_POS_X] = NVSJSON_INITINT32_RNG("S1.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT1_POS_Y] = NVSJSON_INITINT32_RNG("S1.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT1_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S1.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT2_POS_X] = NVSJSON_INITINT32_RNG("S2.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT2_POS_Y] = NVSJSON_INITINT32_RNG("S2.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT2_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S2.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT3_POS_X] = NVSJSON_INITINT32_RNG("S3.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT3_POS_Y] = NVSJSON_INITINT32_RNG("S3.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT3_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S3.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT4_POS_X] = NVSJSON_INITINT32_RNG("S4.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT4_POS_Y] = NVSJSON_INITINT32_RNG("S4.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT4_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S4.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT5_POS_X] = NVSJSON_INITINT32_RNG("S5.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT5_POS_Y] = NVSJSON_INITINT32_RNG("S5.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT5_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S5.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT6_POS_X] = NVSJSON_INITINT32_RNG("S6.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT6_POS_Y] = NVSJSON_INITINT32_RNG("S6.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT6_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S6.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT7_POS_X] = NVSJSON_INITINT32_RNG("S7.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT7_POS_Y] = NVSJSON_INITINT32_RNG("S7.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT7_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S7.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT8_POS_X] = NVSJSON_INITINT32_RNG("S8.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT8_POS_Y] = NVSJSON_INITINT32_RNG("S8.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT8_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S8.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT9_POS_X] = NVSJSON_INITINT32_RNG("S9.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT9_POS_Y] = NVSJSON_INITINT32_RNG("S9.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT9_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S9.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT10_POS_X] = NVSJSON_INITINT32_RNG("S10.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT10_POS_Y] = NVSJSON_INITINT32_RNG("S10.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT10_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S10.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT11_POS_X] = NVSJSON_INITINT32_RNG("S11.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT11_POS_Y] = NVSJSON_INITINT32_RNG("S11.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT11_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S11.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT12_POS_X] = NVSJSON_INITINT32_RNG("S12.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT12_POS_Y] = NVSJSON_INITINT32_RNG("S12.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT12_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S12.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT13_POS_X] = NVSJSON_INITINT32_RNG("S13.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT13_POS_Y] = NVSJSON_INITINT32_RNG("S13.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT13_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S13.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT14_POS_X] = NVSJSON_INITINT32_RNG("S14.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT14_POS_Y] = NVSJSON_INITINT32_RNG("S14.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT14_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S14.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT15_POS_X] = NVSJSON_INITINT32_RNG("S15.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT15_POS_Y] = NVSJSON_INITINT32_RNG("S15.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT15_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S15.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),

    [SETTINGS_EENTRY_SLOT16_POS_X] = NVSJSON_INITINT32_RNG("S16.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT16_POS_Y] = NVSJSON_INITINT32_RNG("S16.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [SETTINGS_EENTRY_SLOT16_POS_INGREDIENTID] = NVSJSON_INITINT32_RNG("S16.IngreID", "Ingredient ID", 0, 0, 100000, NVSJSON_EFLAGS_None),
};

void SETTINGS_Init()
{
    NVSJSON_Init(&g_sSettingHandle, g_sConfigEntries, SETTINGS_EENTRY_Count);
}

static bool ValidateWifiPassword(const NVSJSON_SSettingEntry* pSettingEntry, const char* szValue)
{
    const size_t n = strlen(szValue);
    return n > 8 || n == 0;
}