#ifndef _SETTING_H_
#define _SETTING_H_

#include "nvsjson.h"

typedef enum
{
    SETTINGS_EENTRY_WAPPass,

    SETTINGS_EENTRY_WSTAIsActive,
    SETTINGS_EENTRY_WSTASSID,
    SETTINGS_EENTRY_WSTAPass,

    // Slots section
    SETTINGS_EENTRY_SLOT1_POS_X,
    SETTINGS_EENTRY_SLOT1_POS_Y,
    SETTINGS_EENTRY_SLOT1_LOADID,
    SETTINGS_EENTRY_SLOT1_TOTALQTY,
    SETTINGS_EENTRY_SLOT1_USEDQTY,

    SETTINGS_EENTRY_SLOT2_POS_X,
    SETTINGS_EENTRY_SLOT2_POS_Y,
    SETTINGS_EENTRY_SLOT2_LOADID,
    SETTINGS_EENTRY_SLOT2_TOTALQTY,
    SETTINGS_EENTRY_SLOT2_USEDQTY,

    SETTINGS_EENTRY_SLOT3_POS_X,
    SETTINGS_EENTRY_SLOT3_POS_Y,
    SETTINGS_EENTRY_SLOT3_LOADID,
    SETTINGS_EENTRY_SLOT3_TOTALQTY,
    SETTINGS_EENTRY_SLOT3_USEDQTY,

    SETTINGS_EENTRY_SLOT4_POS_X,
    SETTINGS_EENTRY_SLOT4_POS_Y,
    SETTINGS_EENTRY_SLOT4_LOADID,
    SETTINGS_EENTRY_SLOT4_TOTALQTY,
    SETTINGS_EENTRY_SLOT4_USEDQTY,

    SETTINGS_EENTRY_SLOT5_POS_X,
    SETTINGS_EENTRY_SLOT5_POS_Y,
    SETTINGS_EENTRY_SLOT5_LOADID,
    SETTINGS_EENTRY_SLOT5_TOTALQTY,
    SETTINGS_EENTRY_SLOT5_USEDQTY,

    SETTINGS_EENTRY_SLOT6_POS_X,
    SETTINGS_EENTRY_SLOT6_POS_Y,
    SETTINGS_EENTRY_SLOT6_LOADID,
    SETTINGS_EENTRY_SLOT6_TOTALQTY,
    SETTINGS_EENTRY_SLOT6_USEDQTY,

    SETTINGS_EENTRY_SLOT7_POS_X,
    SETTINGS_EENTRY_SLOT7_POS_Y,
    SETTINGS_EENTRY_SLOT7_LOADID,
    SETTINGS_EENTRY_SLOT7_TOTALQTY,
    SETTINGS_EENTRY_SLOT7_USEDQTY,

    SETTINGS_EENTRY_SLOT8_POS_X,
    SETTINGS_EENTRY_SLOT8_POS_Y,
    SETTINGS_EENTRY_SLOT8_LOADID,
    SETTINGS_EENTRY_SLOT8_TOTALQTY,
    SETTINGS_EENTRY_SLOT8_USEDQTY,

    SETTINGS_EENTRY_SLOT9_POS_X,
    SETTINGS_EENTRY_SLOT9_POS_Y,
    SETTINGS_EENTRY_SLOT9_LOADID,
    SETTINGS_EENTRY_SLOT9_TOTALQTY,
    SETTINGS_EENTRY_SLOT9_USEDQTY,

    SETTINGS_EENTRY_SLOT10_POS_X,
    SETTINGS_EENTRY_SLOT10_POS_Y,
    SETTINGS_EENTRY_SLOT10_LOADID,
    SETTINGS_EENTRY_SLOT10_TOTALQTY,
    SETTINGS_EENTRY_SLOT10_USEDQTY,

    SETTINGS_EENTRY_SLOT11_POS_X,
    SETTINGS_EENTRY_SLOT11_POS_Y,
    SETTINGS_EENTRY_SLOT11_LOADID,
    SETTINGS_EENTRY_SLOT11_TOTALQTY,
    SETTINGS_EENTRY_SLOT11_USEDQTY,

    SETTINGS_EENTRY_SLOT12_POS_X,
    SETTINGS_EENTRY_SLOT12_POS_Y,
    SETTINGS_EENTRY_SLOT12_LOADID,
    SETTINGS_EENTRY_SLOT12_TOTALQTY,
    SETTINGS_EENTRY_SLOT12_USEDQTY,

    SETTINGS_EENTRY_SLOT13_POS_X,
    SETTINGS_EENTRY_SLOT13_POS_Y,
    SETTINGS_EENTRY_SLOT13_LOADID,
    SETTINGS_EENTRY_SLOT13_TOTALQTY,
    SETTINGS_EENTRY_SLOT13_USEDQTY,

    SETTINGS_EENTRY_SLOT14_POS_X,
    SETTINGS_EENTRY_SLOT14_POS_Y,
    SETTINGS_EENTRY_SLOT14_LOADID,
    SETTINGS_EENTRY_SLOT14_TOTALQTY,
    SETTINGS_EENTRY_SLOT14_USEDQTY,

    SETTINGS_EENTRY_SLOT15_POS_X,
    SETTINGS_EENTRY_SLOT15_POS_Y,
    SETTINGS_EENTRY_SLOT15_LOADID,
    SETTINGS_EENTRY_SLOT15_TOTALQTY,
    SETTINGS_EENTRY_SLOT15_USEDQTY,

    SETTINGS_EENTRY_SLOT16_POS_X,
    SETTINGS_EENTRY_SLOT16_POS_Y,
    SETTINGS_EENTRY_SLOT16_LOADID,
    SETTINGS_EENTRY_SLOT16_TOTALQTY,
    SETTINGS_EENTRY_SLOT16_USEDQTY,

    SETTINGS_EENTRY_Count
} SETTINGS_EENTRY;

void SETTINGS_Init();

extern NVSJSON_SHandle g_sSettingHandle;

#endif