#ifndef _SETTING_H_
#define _SETTING_H_

#include "nvsjson.h"

typedef enum
{
    SETTINGS_EENTRY_WAPPass,

    SETTINGS_EENTRY_WSTAIsActive,
    SETTINGS_EENTRY_WSTASSID,
    SETTINGS_EENTRY_WSTAPass,

    // Slots section
    // Block #1
    SETTINGS_EENTRY_SLOT1_POS_X,
    SETTINGS_EENTRY_SLOT1_POS_Y,
    SETTINGS_EENTRY_SLOT1_POS_INGREDIENTID,

    SETTINGS_EENTRY_SLOT2_POS_X,
    SETTINGS_EENTRY_SLOT2_POS_Y,
    SETTINGS_EENTRY_SLOT2_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT3_POS_X,
    SETTINGS_EENTRY_SLOT3_POS_Y,
    SETTINGS_EENTRY_SLOT3_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT4_POS_X,
    SETTINGS_EENTRY_SLOT4_POS_Y,
    SETTINGS_EENTRY_SLOT4_POS_INGREDIENTID,

    // Block #2
    SETTINGS_EENTRY_SLOT5_POS_X,
    SETTINGS_EENTRY_SLOT5_POS_Y,
    SETTINGS_EENTRY_SLOT5_POS_INGREDIENTID,

    SETTINGS_EENTRY_SLOT6_POS_X,
    SETTINGS_EENTRY_SLOT6_POS_Y,
    SETTINGS_EENTRY_SLOT6_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT7_POS_X,
    SETTINGS_EENTRY_SLOT7_POS_Y,
    SETTINGS_EENTRY_SLOT7_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT8_POS_X,
    SETTINGS_EENTRY_SLOT8_POS_Y,
    SETTINGS_EENTRY_SLOT8_POS_INGREDIENTID,

    // Block #3
    SETTINGS_EENTRY_SLOT9_POS_X,
    SETTINGS_EENTRY_SLOT9_POS_Y,
    SETTINGS_EENTRY_SLOT9_POS_INGREDIENTID,

    SETTINGS_EENTRY_SLOT10_POS_X,
    SETTINGS_EENTRY_SLOT10_POS_Y,
    SETTINGS_EENTRY_SLOT10_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT11_POS_X,
    SETTINGS_EENTRY_SLOT11_POS_Y,
    SETTINGS_EENTRY_SLOT11_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT12_POS_X,
    SETTINGS_EENTRY_SLOT12_POS_Y,
    SETTINGS_EENTRY_SLOT12_POS_INGREDIENTID,

    // Block #4
    SETTINGS_EENTRY_SLOT13_POS_X,
    SETTINGS_EENTRY_SLOT13_POS_Y,
    SETTINGS_EENTRY_SLOT13_POS_INGREDIENTID,

    SETTINGS_EENTRY_SLOT14_POS_X,
    SETTINGS_EENTRY_SLOT14_POS_Y,
    SETTINGS_EENTRY_SLOT14_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT15_POS_X,
    SETTINGS_EENTRY_SLOT15_POS_Y,
    SETTINGS_EENTRY_SLOT15_POS_INGREDIENTID,
    
    SETTINGS_EENTRY_SLOT16_POS_X,
    SETTINGS_EENTRY_SLOT16_POS_Y,
    SETTINGS_EENTRY_SLOT16_POS_INGREDIENTID,

    SETTINGS_EENTRY_Count
} SETTINGS_EENTRY;

void SETTINGS_Init();

extern NVSJSON_SHandle g_sSettingHandle;

#endif