#ifndef _SETTING_H_
#define _SETTING_H_

#include "nvsjson.h"

typedef enum
{
    SETTINGS_EENTRY_WAPPass,

    SETTINGS_EENTRY_WSTAIsActive,
    SETTINGS_EENTRY_WSTASSID,
    SETTINGS_EENTRY_WSTAPass,

    // Stations section
    SETTINGS_EENTRY_STATION1_POS_X,
    SETTINGS_EENTRY_STATION1_POS_Y,
    SETTINGS_EENTRY_STATION1_LOADID,
    SETTINGS_EENTRY_STATION1_TOTALQTY,
    SETTINGS_EENTRY_STATION1_USEDQTY,

    SETTINGS_EENTRY_STATION2_POS_X,
    SETTINGS_EENTRY_STATION2_POS_Y,
    SETTINGS_EENTRY_STATION2_LOADID,
    SETTINGS_EENTRY_STATION2_TOTALQTY,
    SETTINGS_EENTRY_STATION2_USEDQTY,

    SETTINGS_EENTRY_STATION3_POS_X,
    SETTINGS_EENTRY_STATION3_POS_Y,
    SETTINGS_EENTRY_STATION3_LOADID,
    SETTINGS_EENTRY_STATION3_TOTALQTY,
    SETTINGS_EENTRY_STATION3_USEDQTY,

    SETTINGS_EENTRY_STATION4_POS_X,
    SETTINGS_EENTRY_STATION4_POS_Y,
    SETTINGS_EENTRY_STATION4_LOADID,
    SETTINGS_EENTRY_STATION4_TOTALQTY,
    SETTINGS_EENTRY_STATION4_USEDQTY,

    SETTINGS_EENTRY_STATION5_POS_X,
    SETTINGS_EENTRY_STATION5_POS_Y,
    SETTINGS_EENTRY_STATION5_LOADID,
    SETTINGS_EENTRY_STATION5_TOTALQTY,
    SETTINGS_EENTRY_STATION5_USEDQTY,

    SETTINGS_EENTRY_STATION6_POS_X,
    SETTINGS_EENTRY_STATION6_POS_Y,
    SETTINGS_EENTRY_STATION6_LOADID,
    SETTINGS_EENTRY_STATION6_TOTALQTY,
    SETTINGS_EENTRY_STATION6_USEDQTY,

    SETTINGS_EENTRY_STATION7_POS_X,
    SETTINGS_EENTRY_STATION7_POS_Y,
    SETTINGS_EENTRY_STATION7_LOADID,
    SETTINGS_EENTRY_STATION7_TOTALQTY,
    SETTINGS_EENTRY_STATION7_USEDQTY,

    SETTINGS_EENTRY_STATION8_POS_X,
    SETTINGS_EENTRY_STATION8_POS_Y,
    SETTINGS_EENTRY_STATION8_LOADID,
    SETTINGS_EENTRY_STATION8_TOTALQTY,
    SETTINGS_EENTRY_STATION8_USEDQTY,

    SETTINGS_EENTRY_STATION9_POS_X,
    SETTINGS_EENTRY_STATION9_POS_Y,
    SETTINGS_EENTRY_STATION9_LOADID,
    SETTINGS_EENTRY_STATION9_TOTALQTY,
    SETTINGS_EENTRY_STATION9_USEDQTY,

    SETTINGS_EENTRY_STATION10_POS_X,
    SETTINGS_EENTRY_STATION10_POS_Y,
    SETTINGS_EENTRY_STATION10_LOADID,
    SETTINGS_EENTRY_STATION10_TOTALQTY,
    SETTINGS_EENTRY_STATION10_USEDQTY,

    SETTINGS_EENTRY_STATION11_POS_X,
    SETTINGS_EENTRY_STATION11_POS_Y,
    SETTINGS_EENTRY_STATION11_LOADID,
    SETTINGS_EENTRY_STATION11_TOTALQTY,
    SETTINGS_EENTRY_STATION11_USEDQTY,

    SETTINGS_EENTRY_STATION12_POS_X,
    SETTINGS_EENTRY_STATION12_POS_Y,
    SETTINGS_EENTRY_STATION12_LOADID,
    SETTINGS_EENTRY_STATION12_TOTALQTY,
    SETTINGS_EENTRY_STATION12_USEDQTY,

    SETTINGS_EENTRY_STATION13_POS_X,
    SETTINGS_EENTRY_STATION13_POS_Y,
    SETTINGS_EENTRY_STATION13_LOADID,
    SETTINGS_EENTRY_STATION13_TOTALQTY,
    SETTINGS_EENTRY_STATION13_USEDQTY,

    SETTINGS_EENTRY_STATION14_POS_X,
    SETTINGS_EENTRY_STATION14_POS_Y,
    SETTINGS_EENTRY_STATION14_LOADID,
    SETTINGS_EENTRY_STATION14_TOTALQTY,
    SETTINGS_EENTRY_STATION14_USEDQTY,

    SETTINGS_EENTRY_STATION15_POS_X,
    SETTINGS_EENTRY_STATION15_POS_Y,
    SETTINGS_EENTRY_STATION15_LOADID,
    SETTINGS_EENTRY_STATION15_TOTALQTY,
    SETTINGS_EENTRY_STATION15_USEDQTY,

    SETTINGS_EENTRY_STATION16_POS_X,
    SETTINGS_EENTRY_STATION16_POS_Y,
    SETTINGS_EENTRY_STATION16_LOADID,
    SETTINGS_EENTRY_STATION16_TOTALQTY,
    SETTINGS_EENTRY_STATION16_USEDQTY,

    SETTINGS_EENTRY_Count
} SETTINGS_EENTRY;

void SETTINGS_Init();

extern NVSJSON_SHandle g_sSettingHandle;

#endif