#include "StationSettings.h"
#include <string.h>

NVSJSON_SHandle g_sStationSettingHandle;

static const NVSJSON_SSettingEntry m_arrsConfigEntries[STATIONSETTINGS_EENTRY_Count] =
{
    [STATIONSETTINGS_EENTRY_STATION_1_PosX] = NVSJSON_INITINT32_RNG("S1.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_1_PosY] = NVSJSON_INITINT32_RNG("S1.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_1_LoadID] = NVSJSON_INITINT32_RNG("S1.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_1_TotalQty] = NVSJSON_INITINT32_RNG("S1.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_1_UsedQty] = NVSJSON_INITINT32_RNG("S1.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_2_PosX] = NVSJSON_INITINT32_RNG("S2.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_2_PosY] = NVSJSON_INITINT32_RNG("S2.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_2_LoadID] = NVSJSON_INITINT32_RNG("S2.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_2_TotalQty] = NVSJSON_INITINT32_RNG("S2.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_2_UsedQty] = NVSJSON_INITINT32_RNG("S2.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_3_PosX] = NVSJSON_INITINT32_RNG("S3.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_3_PosY] = NVSJSON_INITINT32_RNG("S3.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_3_LoadID] = NVSJSON_INITINT32_RNG("S3.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_3_TotalQty] = NVSJSON_INITINT32_RNG("S3.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_3_UsedQty] = NVSJSON_INITINT32_RNG("S3.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_4_PosX] = NVSJSON_INITINT32_RNG("S4.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_4_PosY] = NVSJSON_INITINT32_RNG("S4.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_4_LoadID] = NVSJSON_INITINT32_RNG("S4.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_4_TotalQty] = NVSJSON_INITINT32_RNG("S4.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_4_UsedQty] = NVSJSON_INITINT32_RNG("S4.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_5_PosX] = NVSJSON_INITINT32_RNG("S5.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_5_PosY] = NVSJSON_INITINT32_RNG("S5.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_5_LoadID] = NVSJSON_INITINT32_RNG("S5.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_5_TotalQty] = NVSJSON_INITINT32_RNG("S5.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_5_UsedQty] = NVSJSON_INITINT32_RNG("S5.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_6_PosX] = NVSJSON_INITINT32_RNG("S6.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_6_PosY] = NVSJSON_INITINT32_RNG("S6.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_6_LoadID] = NVSJSON_INITINT32_RNG("S6.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_6_TotalQty] = NVSJSON_INITINT32_RNG("S6.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_6_UsedQty] = NVSJSON_INITINT32_RNG("S6.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_7_PosX] = NVSJSON_INITINT32_RNG("S7.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_7_PosY] = NVSJSON_INITINT32_RNG("S7.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_7_LoadID] = NVSJSON_INITINT32_RNG("S7.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_7_TotalQty] = NVSJSON_INITINT32_RNG("S7.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_7_UsedQty] = NVSJSON_INITINT32_RNG("S7.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_8_PosX] = NVSJSON_INITINT32_RNG("S8.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_8_PosY] = NVSJSON_INITINT32_RNG("S8.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_8_LoadID] = NVSJSON_INITINT32_RNG("S8.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_8_TotalQty] = NVSJSON_INITINT32_RNG("S8.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_8_UsedQty] = NVSJSON_INITINT32_RNG("S8.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_9_PosX] = NVSJSON_INITINT32_RNG("S9.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_9_PosY] = NVSJSON_INITINT32_RNG("S9.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_9_LoadID] = NVSJSON_INITINT32_RNG("S9.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_9_TotalQty] = NVSJSON_INITINT32_RNG("S9.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_9_UsedQty] = NVSJSON_INITINT32_RNG("S9.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_10_PosX] = NVSJSON_INITINT32_RNG("S10.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_10_PosY] = NVSJSON_INITINT32_RNG("S10.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_10_LoadID] = NVSJSON_INITINT32_RNG("S10.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_10_TotalQty] = NVSJSON_INITINT32_RNG("S10.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_10_UsedQty] = NVSJSON_INITINT32_RNG("S10.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_11_PosX] = NVSJSON_INITINT32_RNG("S11.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_11_PosY] = NVSJSON_INITINT32_RNG("S11.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_11_LoadID] = NVSJSON_INITINT32_RNG("S11.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_11_TotalQty] = NVSJSON_INITINT32_RNG("S11.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_11_UsedQty] = NVSJSON_INITINT32_RNG("S11.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_12_PosX] = NVSJSON_INITINT32_RNG("S12.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_12_PosY] = NVSJSON_INITINT32_RNG("S12.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_12_LoadID] = NVSJSON_INITINT32_RNG("S12.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_12_TotalQty] = NVSJSON_INITINT32_RNG("S12.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_12_UsedQty] = NVSJSON_INITINT32_RNG("S12.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_13_PosX] = NVSJSON_INITINT32_RNG("S13.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_13_PosY] = NVSJSON_INITINT32_RNG("S13.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_13_LoadID] = NVSJSON_INITINT32_RNG("S13.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_13_TotalQty] = NVSJSON_INITINT32_RNG("S13.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_13_UsedQty] = NVSJSON_INITINT32_RNG("S13.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_14_PosX] = NVSJSON_INITINT32_RNG("S14.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_14_PosY] = NVSJSON_INITINT32_RNG("S14.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_14_LoadID] = NVSJSON_INITINT32_RNG("S14.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_14_TotalQty] = NVSJSON_INITINT32_RNG("S14.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_14_UsedQty] = NVSJSON_INITINT32_RNG("S14.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_15_PosX] = NVSJSON_INITINT32_RNG("S15.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_15_PosY] = NVSJSON_INITINT32_RNG("S15.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_15_LoadID] = NVSJSON_INITINT32_RNG("S15.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_15_TotalQty] = NVSJSON_INITINT32_RNG("S15.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_15_UsedQty] = NVSJSON_INITINT32_RNG("S15.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_16_PosX] = NVSJSON_INITINT32_RNG("S16.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_16_PosY] = NVSJSON_INITINT32_RNG("S16.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_16_LoadID] = NVSJSON_INITINT32_RNG("S16.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_16_TotalQty] = NVSJSON_INITINT32_RNG("S16.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_16_UsedQty] = NVSJSON_INITINT32_RNG("S16.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_17_PosX] = NVSJSON_INITINT32_RNG("S17.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_17_PosY] = NVSJSON_INITINT32_RNG("S17.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_17_LoadID] = NVSJSON_INITINT32_RNG("S17.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_17_TotalQty] = NVSJSON_INITINT32_RNG("S17.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_17_UsedQty] = NVSJSON_INITINT32_RNG("S17.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_18_PosX] = NVSJSON_INITINT32_RNG("S18.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_18_PosY] = NVSJSON_INITINT32_RNG("S18.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_18_LoadID] = NVSJSON_INITINT32_RNG("S18.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_18_TotalQty] = NVSJSON_INITINT32_RNG("S18.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_18_UsedQty] = NVSJSON_INITINT32_RNG("S18.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_19_PosX] = NVSJSON_INITINT32_RNG("S19.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_19_PosY] = NVSJSON_INITINT32_RNG("S19.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_19_LoadID] = NVSJSON_INITINT32_RNG("S19.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_19_TotalQty] = NVSJSON_INITINT32_RNG("S19.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_19_UsedQty] = NVSJSON_INITINT32_RNG("S19.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_20_PosX] = NVSJSON_INITINT32_RNG("S20.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_20_PosY] = NVSJSON_INITINT32_RNG("S20.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_20_LoadID] = NVSJSON_INITINT32_RNG("S20.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_20_TotalQty] = NVSJSON_INITINT32_RNG("S20.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_20_UsedQty] = NVSJSON_INITINT32_RNG("S20.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_21_PosX] = NVSJSON_INITINT32_RNG("S21.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_21_PosY] = NVSJSON_INITINT32_RNG("S21.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_21_LoadID] = NVSJSON_INITINT32_RNG("S21.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_21_TotalQty] = NVSJSON_INITINT32_RNG("S21.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_21_UsedQty] = NVSJSON_INITINT32_RNG("S21.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_22_PosX] = NVSJSON_INITINT32_RNG("S22.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_22_PosY] = NVSJSON_INITINT32_RNG("S22.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_22_LoadID] = NVSJSON_INITINT32_RNG("S22.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_22_TotalQty] = NVSJSON_INITINT32_RNG("S22.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_22_UsedQty] = NVSJSON_INITINT32_RNG("S22.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION_23_PosX] = NVSJSON_INITINT32_RNG("S23.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_23_PosY] = NVSJSON_INITINT32_RNG("S23.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_23_LoadID] = NVSJSON_INITINT32_RNG("S23.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_23_TotalQty] = NVSJSON_INITINT32_RNG("S23.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION_23_UsedQty] = NVSJSON_INITINT32_RNG("S23.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None)
};

static const NVSJSON_SConfig m_sConfig = { .szNamespace = "stationcfg" };

void STATIONSETTINGS_Init()
{
    NVSJSON_Init(&g_sStationSettingHandle, &m_sConfig, m_arrsConfigEntries, STATIONSETTINGS_EENTRY_Count);
}

int32_t STATIONSETTINGS_GetValue(int stationId, STATIONSETTINGS_ESTATIONSET eStationSet)
{
    if (!STATIONSETTINGS_ISVALIDSTATIONID(stationId))
        return 0;
    int ix0b = stationId - 1;
    const STATIONSETTINGS_EENTRY eEntry = (STATIONSETTINGS_EENTRY)((ix0b * STATIONSETTINGS_ESTATIONSET_Count) + (int)eStationSet);
    return NVSJSON_GetValueInt32(&g_sStationSettingHandle, (uint16_t)eEntry);
}

NVSJSON_ESETRET STATIONSETTINGS_SetValue(int stationId, STATIONSETTINGS_ESTATIONSET eStationSet, int32_t s32Value)
{
    if (!STATIONSETTINGS_ISVALIDSTATIONID(stationId))
        return 0;
    int ix0b = stationId - 1;
    const STATIONSETTINGS_EENTRY eEntry = (STATIONSETTINGS_EENTRY)((ix0b * STATIONSETTINGS_ESTATIONSET_Count) + (int)eStationSet);
    return NVSJSON_SetValueInt32(&g_sStationSettingHandle, (uint16_t)eEntry, false, s32Value);
}

void STATIONSETTINGS_CommitAll()
{
    NVSJSON_Save(&g_sStationSettingHandle);
}