#include "StationSettings.h"
#include <string.h>

NVSJSON_SHandle g_sStationSettingHandle;

static const NVSJSON_SSettingEntry m_arrsConfigEntries[STATIONSETTINGS_EENTRY_Count] =
{
    // Stations
    [STATIONSETTINGS_EENTRY_STATION1_PosX] = NVSJSON_INITINT32_RNG("S1.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION1_PosY] = NVSJSON_INITINT32_RNG("S1.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION1_LoadID] = NVSJSON_INITINT32_RNG("S1.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION1_TotalQty] = NVSJSON_INITINT32_RNG("S1.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION1_UsedQty] = NVSJSON_INITINT32_RNG("S1.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION2_PosX] = NVSJSON_INITINT32_RNG("S2.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION2_PosY] = NVSJSON_INITINT32_RNG("S2.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION2_LoadID] = NVSJSON_INITINT32_RNG("S2.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION2_TotalQty] = NVSJSON_INITINT32_RNG("S2.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION2_UsedQty] = NVSJSON_INITINT32_RNG("S2.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION3_PosX] = NVSJSON_INITINT32_RNG("S3.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION3_PosY] = NVSJSON_INITINT32_RNG("S3.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION3_LoadID] = NVSJSON_INITINT32_RNG("S3.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION3_TotalQty] = NVSJSON_INITINT32_RNG("S3.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION3_UsedQty] = NVSJSON_INITINT32_RNG("S3.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION4_PosX] = NVSJSON_INITINT32_RNG("S4.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION4_PosY] = NVSJSON_INITINT32_RNG("S4.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION4_LoadID] = NVSJSON_INITINT32_RNG("S4.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION4_TotalQty] = NVSJSON_INITINT32_RNG("S4.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION4_UsedQty] = NVSJSON_INITINT32_RNG("S4.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION5_PosX] = NVSJSON_INITINT32_RNG("S5.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION5_PosY] = NVSJSON_INITINT32_RNG("S5.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION5_LoadID] = NVSJSON_INITINT32_RNG("S5.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION5_TotalQty] = NVSJSON_INITINT32_RNG("S5.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION5_UsedQty] = NVSJSON_INITINT32_RNG("S5.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION6_PosX] = NVSJSON_INITINT32_RNG("S6.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION6_PosY] = NVSJSON_INITINT32_RNG("S6.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION6_LoadID] = NVSJSON_INITINT32_RNG("S6.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION6_TotalQty] = NVSJSON_INITINT32_RNG("S6.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION6_UsedQty] = NVSJSON_INITINT32_RNG("S6.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION7_PosX] = NVSJSON_INITINT32_RNG("S7.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION7_PosY] = NVSJSON_INITINT32_RNG("S7.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION7_LoadID] = NVSJSON_INITINT32_RNG("S7.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION7_TotalQty] = NVSJSON_INITINT32_RNG("S7.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION7_UsedQty] = NVSJSON_INITINT32_RNG("S7.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION8_PosX] = NVSJSON_INITINT32_RNG("S8.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION8_PosY] = NVSJSON_INITINT32_RNG("S8.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION8_LoadID] = NVSJSON_INITINT32_RNG("S8.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION8_TotalQty] = NVSJSON_INITINT32_RNG("S8.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION8_UsedQty] = NVSJSON_INITINT32_RNG("S8.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION9_PosX] = NVSJSON_INITINT32_RNG("S9.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION9_PosY] = NVSJSON_INITINT32_RNG("S9.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION9_LoadID] = NVSJSON_INITINT32_RNG("S9.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION9_TotalQty] = NVSJSON_INITINT32_RNG("S9.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION9_UsedQty] = NVSJSON_INITINT32_RNG("S9.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION10_PosX] = NVSJSON_INITINT32_RNG("S10.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION10_PosY] = NVSJSON_INITINT32_RNG("S10.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION10_LoadID] = NVSJSON_INITINT32_RNG("S10.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION10_TotalQty] = NVSJSON_INITINT32_RNG("S10.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION10_UsedQty] = NVSJSON_INITINT32_RNG("S10.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION11_PosX] = NVSJSON_INITINT32_RNG("S11.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION11_PosY] = NVSJSON_INITINT32_RNG("S11.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION11_LoadID] = NVSJSON_INITINT32_RNG("S11.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION11_TotalQty] = NVSJSON_INITINT32_RNG("S11.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION11_UsedQty] = NVSJSON_INITINT32_RNG("S11.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION12_PosX] = NVSJSON_INITINT32_RNG("S12.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION12_PosY] = NVSJSON_INITINT32_RNG("S12.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION12_LoadID] = NVSJSON_INITINT32_RNG("S12.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION12_TotalQty] = NVSJSON_INITINT32_RNG("S12.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION12_UsedQty] = NVSJSON_INITINT32_RNG("S12.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION13_PosX] = NVSJSON_INITINT32_RNG("S13.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION13_PosY] = NVSJSON_INITINT32_RNG("S13.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION13_LoadID] = NVSJSON_INITINT32_RNG("S13.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION13_TotalQty] = NVSJSON_INITINT32_RNG("S13.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION13_UsedQty] = NVSJSON_INITINT32_RNG("S13.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION14_PosX] = NVSJSON_INITINT32_RNG("S14.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION14_PosY] = NVSJSON_INITINT32_RNG("S14.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION14_LoadID] = NVSJSON_INITINT32_RNG("S14.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION14_TotalQty] = NVSJSON_INITINT32_RNG("S14.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION14_UsedQty] = NVSJSON_INITINT32_RNG("S14.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION15_PosX] = NVSJSON_INITINT32_RNG("S15.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION15_PosY] = NVSJSON_INITINT32_RNG("S15.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION15_LoadID] = NVSJSON_INITINT32_RNG("S15.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION15_TotalQty] = NVSJSON_INITINT32_RNG("S15.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION15_UsedQty] = NVSJSON_INITINT32_RNG("S15.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),

    [STATIONSETTINGS_EENTRY_STATION16_PosX] = NVSJSON_INITINT32_RNG("S16.PosX", "Position X", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION16_PosY] = NVSJSON_INITINT32_RNG("S16.PosY", "Position Y", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION16_LoadID] = NVSJSON_INITINT32_RNG("S16.LoadID", "Ingredient ID, 0 = nothing", 0, 0, 100000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION16_TotalQty] = NVSJSON_INITINT32_RNG("S16.TotalML", "Total Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None),
    [STATIONSETTINGS_EENTRY_STATION16_UsedQty] = NVSJSON_INITINT32_RNG("S16.UsedML", "Used Qty (ml)", 0, 0, 6000, NVSJSON_EFLAGS_None)
};

static const NVSJSON_SConfig m_sConfig = { .szNamespace = "stationcfg" };

void STATIONSETTINGS_Init()
{
    NVSJSON_Init(&g_sStationSettingHandle, &m_sConfig, m_arrsConfigEntries, STATIONSETTINGS_EENTRY_Count);
}

int32_t STATIONSETTINGS_GetValue(int stationId, STATIONSETTINGS_ESTATIONSET eStationSet)
{
    if (stationId < 1 || stationId > STATIONSETTINGS_STATION_COUNT)
        return 0;
    int ix0b = stationId - 1;
    const STATIONSETTINGS_EENTRY eEntry = (STATIONSETTINGS_EENTRY)((ix0b * STATIONSETTINGS_ESTATIONSET_Count) + (int)eStationSet);
    return NVSJSON_GetValueInt32(&g_sStationSettingHandle, (uint16_t)eEntry);
}