#ifndef _STATIONSETTINGS_H_
#define _STATIONSETTINGS_H_

#include "nvsjson.h"

typedef enum
{
    // Stations section
    STATIONSETTINGS_EENTRY_STATION_1_PosX,
    STATIONSETTINGS_EENTRY_STATION_1_PosZ,
    STATIONSETTINGS_EENTRY_STATION_1_LoadID,
    STATIONSETTINGS_EENTRY_STATION_1_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_1_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_2_PosX,
    STATIONSETTINGS_EENTRY_STATION_2_PosZ,
    STATIONSETTINGS_EENTRY_STATION_2_LoadID,
    STATIONSETTINGS_EENTRY_STATION_2_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_2_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_3_PosX,
    STATIONSETTINGS_EENTRY_STATION_3_PosZ,
    STATIONSETTINGS_EENTRY_STATION_3_LoadID,
    STATIONSETTINGS_EENTRY_STATION_3_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_3_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_4_PosX,
    STATIONSETTINGS_EENTRY_STATION_4_PosZ,
    STATIONSETTINGS_EENTRY_STATION_4_LoadID,
    STATIONSETTINGS_EENTRY_STATION_4_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_4_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_5_PosX,
    STATIONSETTINGS_EENTRY_STATION_5_PosZ,
    STATIONSETTINGS_EENTRY_STATION_5_LoadID,
    STATIONSETTINGS_EENTRY_STATION_5_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_5_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_6_PosX,
    STATIONSETTINGS_EENTRY_STATION_6_PosZ,
    STATIONSETTINGS_EENTRY_STATION_6_LoadID,
    STATIONSETTINGS_EENTRY_STATION_6_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_6_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_7_PosX,
    STATIONSETTINGS_EENTRY_STATION_7_PosZ,
    STATIONSETTINGS_EENTRY_STATION_7_LoadID,
    STATIONSETTINGS_EENTRY_STATION_7_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_7_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_8_PosX,
    STATIONSETTINGS_EENTRY_STATION_8_PosZ,
    STATIONSETTINGS_EENTRY_STATION_8_LoadID,
    STATIONSETTINGS_EENTRY_STATION_8_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_8_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_9_PosX,
    STATIONSETTINGS_EENTRY_STATION_9_PosZ,
    STATIONSETTINGS_EENTRY_STATION_9_LoadID,
    STATIONSETTINGS_EENTRY_STATION_9_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_9_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_10_PosX,
    STATIONSETTINGS_EENTRY_STATION_10_PosZ,
    STATIONSETTINGS_EENTRY_STATION_10_LoadID,
    STATIONSETTINGS_EENTRY_STATION_10_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_10_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_11_PosX,
    STATIONSETTINGS_EENTRY_STATION_11_PosZ,
    STATIONSETTINGS_EENTRY_STATION_11_LoadID,
    STATIONSETTINGS_EENTRY_STATION_11_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_11_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_12_PosX,
    STATIONSETTINGS_EENTRY_STATION_12_PosZ,
    STATIONSETTINGS_EENTRY_STATION_12_LoadID,
    STATIONSETTINGS_EENTRY_STATION_12_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_12_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_13_PosX,
    STATIONSETTINGS_EENTRY_STATION_13_PosZ,
    STATIONSETTINGS_EENTRY_STATION_13_LoadID,
    STATIONSETTINGS_EENTRY_STATION_13_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_13_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_14_PosX,
    STATIONSETTINGS_EENTRY_STATION_14_PosZ,
    STATIONSETTINGS_EENTRY_STATION_14_LoadID,
    STATIONSETTINGS_EENTRY_STATION_14_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_14_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_15_PosX,
    STATIONSETTINGS_EENTRY_STATION_15_PosZ,
    STATIONSETTINGS_EENTRY_STATION_15_LoadID,
    STATIONSETTINGS_EENTRY_STATION_15_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_15_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_16_PosX,
    STATIONSETTINGS_EENTRY_STATION_16_PosZ,
    STATIONSETTINGS_EENTRY_STATION_16_LoadID,
    STATIONSETTINGS_EENTRY_STATION_16_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_16_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_17_PosX,
    STATIONSETTINGS_EENTRY_STATION_17_PosZ,
    STATIONSETTINGS_EENTRY_STATION_17_LoadID,
    STATIONSETTINGS_EENTRY_STATION_17_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_17_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_18_PosX,
    STATIONSETTINGS_EENTRY_STATION_18_PosZ,
    STATIONSETTINGS_EENTRY_STATION_18_LoadID,
    STATIONSETTINGS_EENTRY_STATION_18_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_18_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_19_PosX,
    STATIONSETTINGS_EENTRY_STATION_19_PosZ,
    STATIONSETTINGS_EENTRY_STATION_19_LoadID,
    STATIONSETTINGS_EENTRY_STATION_19_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_19_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_20_PosX,
    STATIONSETTINGS_EENTRY_STATION_20_PosZ,
    STATIONSETTINGS_EENTRY_STATION_20_LoadID,
    STATIONSETTINGS_EENTRY_STATION_20_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_20_UsedQty,

    STATIONSETTINGS_EENTRY_STATION_21_PosX,
    STATIONSETTINGS_EENTRY_STATION_21_PosZ,
    STATIONSETTINGS_EENTRY_STATION_21_LoadID,
    STATIONSETTINGS_EENTRY_STATION_21_TotalQty,
    STATIONSETTINGS_EENTRY_STATION_21_UsedQty,

    STATIONSETTINGS_EENTRY_Count
} STATIONSETTINGS_EENTRY;

typedef enum
{
    STATIONSETTINGS_ESTATIONSET_PosX = 0,
    STATIONSETTINGS_ESTATIONSET_PosZ,
    STATIONSETTINGS_ESTATIONSET_LoadID,
    STATIONSETTINGS_ESTATIONSET_TotalQty,
    STATIONSETTINGS_ESTATIONSET_UsedQty,

    STATIONSETTINGS_ESTATIONSET_Count
} STATIONSETTINGS_ESTATIONSET;

#define STATIONSETTINGS_STATION_COUNT (21)
#define STATIONSETTINGS_ISVALIDSTATIONID(_stationid) (_stationid >= 1 && _stationid <= STATIONSETTINGS_STATION_COUNT)
#define STATIONSETTINGS_ISPUMPSTATIONID(_stationid) (_stationid >= 16 && _stationid <= STATIONSETTINGS_STATION_COUNT)

void STATIONSETTINGS_Init();

int32_t STATIONSETTINGS_GetValue(int stationId, STATIONSETTINGS_ESTATIONSET eStationSet);

NVSJSON_ESETRET STATIONSETTINGS_SetValue(int stationId, STATIONSETTINGS_ESTATIONSET eStationSet, int32_t s32Value);

void STATIONSETTINGS_CommitAll();

extern NVSJSON_SHandle g_sStationSettingHandle;

#endif