name: ci

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build (main-fw)
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.3
        path: ./source/main-fw
        target: esp32
